# Generated by Django 4.2.3 on 2023-07-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cost',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='employee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='weekday',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
