# Generated by Django 4.2.3 on 2023-07-27 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_cost_alter_recipe_employee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='cost',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe'),
        ),
    ]
